export const GET_DEAL_REQUEST = "GET_DEAL_REQUEST";
export const GET_DEAL_SUCCESS = "GET_DEAL_SUCCESS";
export const GET_DEAL_FAILURE = "GET_DEAL_FAILURE";

export const GET_DATA_DEAL_REQUEST = "GET_DATA_DEAL_REQUEST";
export const GET_DATA_DEAL_SUCCESS = "GET_DATA_DEAL_SUCCESS";
export const GET_DATA_DEAL_FAILURE = "GET_DATA_DEAL_FAILURE";
