export const GET_DEAL_REQUEST = "GET_DEAL_REQUEST";
export const GET_DEAL_SUCCESS = "GET_DEAL_SUCCESS";
export const GET_DEAL_FAILURE = "GET_DEAL_FAILURE";

export const GET_DATA_DEAL_REQUEST = "GET_DATA_DEAL_REQUEST";
export const GET_DATA_DEAL_SUCCESS = "GET_DATA_DEAL_SUCCESS";
export const GET_DATA_DEAL_FAILURE = "GET_DATA_DEAL_FAILURE";

export const GET_COMMITMENTS_REQUEST = "GET_COMMITMENTS_REQUEST";
export const GET_COMMITMENTS_SUCCESS = "GET_COMMITMENTS_SUCCESS";
export const GET_COMMITMENTS_FAILURE = "GET_COMMITMENTS_FAILURE";

export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAILURE = "GET_STORE_FAILURE";
